### ISSUE TITLE
Dashboards

### ISSUE THREAD

**Issue by primodanilo** [robertson-diasjr/security-labs#1]
Could you please share the json of the dashboards?
Another thing, would it be possible to provide all queries referring to the first graph?

SELECT time, Security_Domain 'Security Domain', AVG(Security_Control_Rate) '%' FROM tracking WHERE Client = 'Client A' AND Security_Domain = 'Application' GROUP BY time;

It is in Security Domains - Lasted Score and has several graphs

![image](https://github.com/user-attachments/assets/81688d85-65cd-4698-b83a-30e8f7d5eac7)

How did you add these other indicators?

Regards
Danilo

**Comment by robertson-diasjr** [comment]
Hi Danilo, I don't have the json anymore, nor the sandbox system to get the queries. The key point is about storing the metrics into DB, then you can create any SQL to match your requirements.
